### ISSUE TITLE
buld fail

### ISSUE THREAD

**Issue by bkr32** [AOSB/android_frameworks_base#11]
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/KeyButtonView.java:147: cannot find symbol
symbol  : class Resources
location: class com.android.systemui.statusbar.policy.KeyButtonView
    public void updateResources(Resources res) {
                                ^
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/PhoneStatusBar.java:3994: cannot find symbol
symbol  : class CustomTheme
location: class com.android.systemui.statusbar.phone.PhoneStatusBar
        CustomTheme newTheme = res.getConfiguration().customTheme;
        ^
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/PhoneStatusBar.java:3994: cannot find symbol
symbol  : variable customTheme
location: class android.content.res.Configuration
        CustomTheme newTheme = res.getConfiguration().customTheme;
                                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

with new commits to framework base status bar

**Comment by animus7** [comment]
![bildschirmfoto vom 2014-07-05 12 19 20](https://cloud.githubusercontent.com/assets/6691581/3486306/df21872e-042d-11e4-92ac-1d9c4d77d03f.png)

**Comment by bkr32** [comment]
same error for now im using framework fork from https://github.com/AudioGod/android_frameworks_base

no hits still error

**Comment by codex-corp** [comment]
been fixed
