### ISSUE TITLE
Reboot to recovery doesn't work

### ISSUE THREAD

**Issue by khusika** [AOSB/android_frameworks_base#15]
When i try to reboot to recovery via power button, it's not boot to recovery but it always reboot to home screen again
Any idea?

**Comment by arnavgosain** [comment]
Can you get any logs?

**Comment by khusika** [comment]
FIXED
Sorry, this is my fault. I just remove this line https://github.com/khusika/android_device_samsung_ancora/commit/c64b7eb9d6ebbf2de94ecdb2e35613c78df2eddb
