### ISSUE TITLE
telephony-common_intermediates/classes-full-debug.jar

### ISSUE THREAD

**Issue by animus7** [AOSB/android_frameworks_base#7]
![bildschirmfoto vom 2014-06-09 16 22 08](https://cloud.githubusercontent.com/assets/6691581/3217651/af995b22-efe1-11e3-86f2-b9400eb201ae.png)
Here you can see:

**Comment by codex-corp** [comment]
thanks ! , it's fixed

**Comment by animus7** [comment]
It is now possible to build or breaks the build again ?
